### ISSUE TITLE
After adding :first_name, :last_name and :gender the tests fall flat

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/bloggerday#2]
https://github.com/wintermeyer/bloggerday/commit/48a787e29fc50069695b074de75feffbe7747d28 added :first_name, :last_name and :gender. Works in development.

But the tests fall flat. Something with the fixtures.

````
 90) test confirm_user/2 does not confirm email if token expired (Bloggerday.AccountsTest)
     test/bloggerday/accounts_test.exs:406
     ** (Postgrex.Error) ERROR 42703 (undefined_column) column "first_name" of relation "users" does not exist
     
         query: INSERT INTO "users" ("email","first_name","gender","hashed_password","last_name","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING "id"
     stacktrace:
       (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto 3.5.5) lib/ecto/repo/schema.ex:649: Ecto.Repo.Schema.apply/4
       (ecto 3.5.5) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (bloggerday 0.1.0) test/support/fixtures/accounts_fixtures.ex:20: Bloggerday.AccountsFixtures.user_fixture/1
       test/bloggerday/accounts_test.exs:382: Bloggerday.AccountsTest.__ex_unit_setup_8/1
       test/bloggerday/accounts_test.exs:1: Bloggerday.AccountsTest.__ex_unit__/2
````

**Comment by wintermeyer** [comment]
Closed by https://github.com/wintermeyer/bloggerday/commit/a4d39e74439585d55c7e9d393e6c2be424ce7bfb
